name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: 'lennahht/sw-random-character'
